CREATE TABLE `trucks` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `truck_id` VARCHAR(50) NOT NULL,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  `last_update` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
